apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: frontend
spec:
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - image: mgrimald/guestbook
        resources:
          requests:
             cpu: 100m
             memory: 100Mi
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
          - containerPort: 80
